service: aws-java-simple-http-endpoint2

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: us-east-2
  
package:
  artifact:  target\aws-java-simple-http-endpoint-dev.jar

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - http:
          path: ping
          method: get
          
plugins:
 - serverless-whitesource
 
custom:
  whitesource:
       pathToConfig: ../whitesource-fs-agent.config
